version: "3"
services:
  web_server_1:
    image: my_web_server
    container_name: web_server_1
    ports:
      - "8081:80"
    networks:
      - web_network

  web_server_2:
    image: my_web_server
    container_name: web_server_2
    ports:
      - "8082:80"
    networks:
      - web_network

  haproxy_1:
    image: haproxy:latest
    container_name: haproxy_1
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web_server_1
      - web_server_2
    networks:
      - web_network

  keepalived_1:
    image: osixia/keepalived
    container_name: keepalived_1
    cap_add:
      - NET_ADMIN
    networks:
      - web_network
    volumes:
      - ./keepalived/keepalived.conf:/etc/keepalived/keepalived.conf

networks:
  web_network:
    driver: bridge
