version: '3'

services:
  web_server_1:
    image: my_web_server
    build:
      context: ./web_server
    container_name: web_server_1
    networks:
      - web_network
    ports:
      - "80:80"

networks:
  web_network:
    driver: bridge
