- name: Deploy Web Servers and Load Balancer
  hosts: localhost
  become: yes
  vars_files:
    - vault.yml

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Build Docker image from web_server directory
      command: sudo docker build -t my_web_server .
      args:
        chdir: "{{ playbook_dir | dirname }}/web_server"

    - name: Start Docker containers using docker-compose
      command: docker-compose -f "{{ playbook_dir | dirname }}/docker-compose.yml" up -d
